### ISSUE TITLE
Thanks for this awsome repo

### ISSUE THREAD

**Issue by N30Z3N** [developeranaz/MEGA-INDEX-CLOUDFLARE#1]
Hi, can i have your username on telegram want to give you something as return, i don't have  crypto or money but this might be useful for you : )

**Comment by developeranaz** [comment]
Thankyou for posting the first issue @bnsave100 
Sorry for the issue , I will keep working to solve your issue.
😊

**Comment by N30Z3N** [comment]
> 
> 
> Thankyou for posting the first issue @bnsave100
> Sorry for the issue , I will keep working to solve your issue.
> 😊

mmmmm please contact me here t.me/slayeroga wanna give u something : )

**Comment by developeranaz** [comment]
thankyou

**Comment by N30Z3N** [comment]
> 
> 
> thankyou

done hope you got my msg : )

**Comment by developeranaz** [comment]
Thank you so much for your compliment.
