### ISSUE TITLE
Download folder not working

### ISSUE THREAD

**Issue by rindishkrishna** [developeranaz/MEGA-INDEX-CLOUDFLARE#12]
how to download all contents of a folder. tried download manager. its just downloading that html page

**Comment by developeranaz** [comment]
> how to download all contents of a folder. tried download manager. its just downloading that html page

The contents of the folder can be downloaded but you need to  scrap all download links of that folder.

You can scrap all links by using [rc-web-scraper](https://github.com/developeranaz/rc-web-scraper) , This works on [Termux on android ](https://f-droid.org/repo/com.termux_117.apk) F-droid version and other linux/unix OS. 

After scraping all download links Use any download managers like Aria2app or any other managers for bulk link download.

If any Further issues, ping here

**Comment by m4heshd** [comment]
@rindishkrishna simply open up your devtools (F12) while inside the directory you want to download, open console tab, paste this and hit enter.

```js
copy(Array.from(document.querySelectorAll('.file a')).map(a => a.href).join('\n'))
```

This will copy all the download links to your clipboard.

**Comment by Gboy06** [comment]
> how to download all contents of a folder. tried download manager. its just downloading that html page

Run site grabber of IDM.
