### ISSUE TITLE
that's amazing..

### ISSUE THREAD

**Issue by irabro1992** [developeranaz/MEGA-INDEX-CLOUDFLARE#3]
hey , thanks for this amazing repo. i want to advice that you should add username & password to protect files directory.

**Comment by developeranaz** [comment]
@irabro1992  Thanks for your advice ,Maybe i will Include username and password in another repo ASAP.

note : If i include username and password section to the index , it may looses its downloading stability.

i.e., the direct link asks password each and every times when your IP changes.

**Comment by developeranaz** [comment]
> hey , thanks for this amazing repo. i want to advice that you should add username & password to protect files directory.

please delete your config after deploying the application in github because config may be exposed to everyone

**Comment by irabro1992** [comment]
> > hey , thanks for this amazing repo. i want to advice that you should add username & password to protect files directory.
> 
> please delete your config after deploying the application in github because config may be exposed to everyone

thanks for the advice. i deleted it.by the way , is it possible to use password for protect the files directory only ?
i hope it will not effect on direct download link when someone download it.

**Comment by developeranaz** [comment]
> > > hey , thanks for this amazing repo. i want to advice that you should add username & password to protect files directory.
> > 
> > 
> > please delete your config after deploying the application in github because config may be exposed to everyone
> 
> thanks for the advice. i deleted it.by the way , is it possible to use password for protect the files directory only ?
> i hope it will not effect on direct download link when someone download it.

I don't know how to add password in directory.
but Maybe i will try to add it in future updates.

**Comment by irabro1992** [comment]
hi , i want to donate you & contact you. please drop me with your telegram account.

**Comment by developeranaz** [comment]
ok ,tg account
https://t.me/gitdeveloperanaz
