### ISSUE TITLE
download limited to 3gb per day

### ISSUE THREAD

**Issue by maheshomf** [developeranaz/MEGA-INDEX-CLOUDFLARE#7]
is there any way to bypass download limit? if we switch account, our data in the cloud drive cannot be retained in all accounts,

**Comment by developeranaz** [comment]
> is there any way to bypass download limit? if we switch account, our data in the cloud drive cannot be retained in all accounts,

I understand this situation. You can overcome this situation by using
1. Use ADM/Aria2/XDM or any download manager with high pause and resume capability. (optional)

2. Pause the download (required)

3. When your MEGA quota is exceeds,  you must access the app settings in Heroku,  click MORE>RESTART DYNO to restart heroku webapp.

4. Then wait a few seconds (20sec) and resume the download.

**Comment by maheshomf** [comment]
Awesome, this works, it was not mentioned in your readme or anywhere!!!!
